### ISSUE TITLE
Json deserialize - imbedded array

### ISSUE THREAD

**Issue by arturEm** [QuickBlox/quickblox-android-sdk#116] opened 2015-09-29 12:25 UTC
In admin panel I store custom object and one of the fields contains json.
In response I can see sth like that:

    STATUS : 200
    HEADERS
    Access-Control-Allow-Origin=*
    Cache-Control=max-age=0, private, must-revalidate
    Connection=keep-alive
    ....
    Server=nginx/1.6.2
    Status=200 OK
    ....
    X-UA-Compatible=IE=Edge,chrome=1
    BODY

  '{"class_name":"MYCLASS","skip":0,"limit":0,"items":[{"JSON":"{\"people\":[[{\"name\":\"JOHN\"},{\"name\":\"JOHN2\"}],[{\"name\":\"MARK\"}],[{\"name\":\"PAUL\"}],[{\"name\":\"TED\"}],[{\"name\":\"MARIA"}],[{\"name\":\"EMO\"}]]}","BackgroundColor":"#FFF","Editable":false,"_id":"XYZID","_parent_id":null,"created_at":19944287,"updated_at":149999351516,"user_id":00001}]}'

it looks okey but QBCustomObject.getFields(JSON) returns this:

[{ people:
{name:JOHN},{ name:JOHN2},{ name:MARK},{ name:PAUL},{ name:TED},{ name:MARIA}, { name:EMO } } ]

insted of

{ people:[
[{name:JOHN},{ name:JOHN2}],[{ name:MARK}],[{ name:PAUL}],[{ name:TED}],[{ name:MARIA}], [{ name:EMO }] ]}

arrays are gone from JSON field

**Comment by soulfly** [comment] 2015-10-13 08:24
The issue is confirmed,

working on it

**Comment by soulfly** [comment] 2015-10-13 09:32
Fixed in development branch
https://github.com/QuickBlox/quickblox-android-sdk/tree/development

will be rolled out in our next release

**Closed by soulfly** 2015-10-13 09:32 UTC
