### ISSUE TITLE
QBRoster  Hello~ Friends request Is there any plan to update the demo?

### ISSUE THREAD

**Issue by pumatus** [QuickBlox/quickblox-android-sdk#715] opened 2020-07-03 09:22 UTC
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by alexparvus1** [comment] 2020-07-21 23:56
Please clarify your comment

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 14:39
@pumatus Hello, 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and provide more detailed information about the issue.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:32
@pumatus The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:32 UTC
