### ISSUE TITLE
Retrieving QBCustomObjets with skip n records not working

### ISSUE THREAD

**Issue by Lovepreet94** [QuickBlox/quickblox-android-sdk#699] opened 2020-03-06 07:41 UTC
In android CustomObjects SDK , skip and limit are   not working and I am always getting  the items in response  . eg . if there are only two records in  database table(i.e class), and I pass skip 2  and limit 50 ,it always returns two records from starting  and arg skip does nothing. code is :

   ```
int startPos = 2;
int pageSize=30;
 QBRequestGetBuilder requestGetBuilder = new QBRequestGetBuilder();
        requestGetBuilder.sortDesc("rating");
        requestGetBuilder.addRule("rating","[calc]","avg");
        requestGetBuilder.addRule("group_by","","_parent_id");
        requestGetBuilder.setSkip(startPos);
        requestGetBuilder.setLimit(pageSize);
    try {
            ArrayList<QBCustomObject> customObjectsDemo 
         =QBCustomObjects.getObjects(Review.Contract.CLASSNAME_REVIEWS,requestGetBuilder)
                    .perform();
 }
```
   response body   is: 
 BODY
        '{"class_name":"Reviews","skip":2,"limit":30,"items":[{"_parent_id":"5e60eb52a28f9a66153831c8","avg":0.0}]}'

> I tried passing the skip value higher than this  e.g (skip= 52), but getting same results every time.

**Comment by alexparvus1** [comment] 2020-04-14 16:30
Please provide the request and response logs.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 13:56
@Lovepreet94 Hello,

This is Nikolay from QuickBlox support.

In order to investigate the issue, please provide us with the following points:
1. Version of the QuickBlox Android SDK.
2. Versions of Android platform where reproduces the issue (e.g. Android 9).
3. Phone models (e.g. Samsung S9).
4 The request in question.
5. The response logs as an attachments in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:30
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:30 UTC
