### ISSUE TITLE
Not Showing my local video and remote video view on caller side

### ISSUE THREAD

**Issue by simranKa** [QuickBlox/quickblox-android-sdk#722] opened 2020-08-06 08:32 UTC
and i have implemented video track listener still unable to get my local video and other caller not getting remote video,  please help me with this issue as soon as possible.

**Comment by alexparvus1** [comment] 2020-08-26 11:30
Please take a look at Sample VideoChat - https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-java  
And if the problem still appears - provide more information about "Not showing video" and "Unable to get video".

Please always provide more information then "I have a problem". 
Please understand - the fact that you have a problem will not help anyone to solve your problem.
It's difficult to help you without any information.
Thanks a lot!

**Comment by simranKa** [comment] 2020-08-27 06:54
hello,

Thank You for your response, actually this issue is resolved. But I am
getting one more issue. The app is working fine in India, but in UAE calls
are cut automatically within 10 sec or more. If you can help me with this,
it's really urgent.

Thanks & Regards
Simran

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:34
@simranKa The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:34 UTC
