### ISSUE TITLE
Attempt to invoke virtual method 'com.siddhi.vl.Util.QBResRequestExecutor com.siddhi.vl.App.getQbResRequestExecutor()' on a null object reference

### ISSUE THREAD

**Issue by prak899** [QuickBlox/quickblox-android-sdk#743] opened 2021-01-23 09:56 UTC
am stuck here almost for a day kindly revert it as fast possiable

**Comment by alexparvus1** [comment] 2021-03-04 19:06
Please give us more information about your issue, maybe some logs etc. And then we can help you.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 16:34
Hello

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and the issue is still relevant.

To investigate the issue, please provide us with the following points:
1. Version of QuickBlox Android SDK.
2. Versions of Android platform where reproduces the issue (e.g. Android 9).
3. Phone models (e.g. Samsung S9).
4. The detailed description of the issue.
5. Please provide us with full logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides)

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:12
@prak899  The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:12 UTC
