### ISSUE TITLE
Error trying to join GroupChat - SDK 2.5.2 to 2.6

### ISSUE THREAD

**Issue by Rhefew** [QuickBlox/quickblox-android-sdk#238] opened 2016-07-04 12:58 UTC
**Environment details**
_(Operating system, browser information, SDK version)_
Ubuntu 15.04, Sdk 2.5.2, Android Studio 2.1.1

**Did this work before?**
Yes

**Expected behavior**
Successful join a Group Chat

**Actual behavior**
Returning the following error 
`com.quickblox.core.exception.QBResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: AndFilter: (FromMatchesFilter (full): 35265_577a58afa28f9a124700000c@muc.chat.quickblox.com/10913617, StanzaTypeFilter: org.jivesoftware.smack.packet.Presence).`

**Steps to reproduce the behavior**
Login, connect to the chat, try to to join the GroupChat after all the initialization.

**Comment by tonchis** [comment] 2016-07-04 13:22
This used to work ok until 06/30/2016.

**Comment by Hemant0601** [comment] 2016-07-05 14:24
@Rhefew check your code if you are not sending any custom property null . In my case it was happening, so my different clients sending the message containing null causing continous drop and then getting this message. Might be not the exact case but just do the sanity.

**Comment by Emeritus-Education** [comment] 2016-07-21 22:24
I'm getting the same error - pretty much suddenly. My code has not changed for months, so there are no custom properties suddenly being set to null. I'm also on 2.5.2.
The error happens at random intervals - it will work fine for a while, then suddenly this line of code will error out with the same error described above:
((GroupChatManagerImpl) mChatManager).joinGroupChat(mRoomId, new QBEntityCallback<Void>() {

**Comment by guimellon** [comment] 2016-08-16 17:32
Could you guys come up with a solution for this problem? I'm facing this issue for some weeks now and as you guys said it used to work perfectly until 06/30.

**Comment by Hemant0601** [comment] 2016-08-17 05:27
@Emeritus-Education and @guimellon Could you please try updating the SDK to 2.6.

**Comment by Emeritus-Education** [comment] 2016-08-17 06:02
No @Hemant0601 . v2.6 has *removed* or simply changed (not just deprecated) several APIs, causing our app to no longer compile. Since this is a production app, we cannot simply move to a higher version of the SDK without knowing for sure that 2.6 has fixed the problem.

**Comment by Hemant0601** [comment] 2016-08-17 07:27
@Emeritus-Education The only change I felt in API was adding user to a roster, might be you are using other APIs too, Please make the changes accordingly in a separate branch and check if it works fine then only you move to production. The custom param might be having some runtime value which can be null at some time which might be causing this, add some logs exactly when you are getting this issue.

**Comment by tatanka987** [comment] 2016-08-17 09:36
hi there. for set other timeout of reply in milliseconds you can use this method before login to the chat QBChatService.setDefaultPacketReplyTimeout(timeout), additional tell information about server what do you use (shared or custom) and add more information about this issue: detail steps to reproduce and more logs

**Comment by darshak4190** [comment] 2016-10-02 14:18
was facing the same issue with quickblox version 2.5.2 . Even upgraded to version 2.6 but no luck. @QuickBlox-team Please look in to it . If the issue has been fixed in the quickblox version 3.0 then please mark it as resolved. The problem with this issue is that it occurs without a specific pattern so there is no way to even test it and be sure about it.

**Comment by Hemant0601** [comment] 2016-10-03 11:34
@darshak4190 Quickblox verison 3.0 is available?

**Comment by darshak4190** [comment] 2016-10-04 07:39
yes they launched it . But that also has issues.

**Comment by NilaySheth** [comment] 2016-10-14 18:34
I am too facing same issue in latest version.

**Comment by lojol** [comment] 2016-11-24 07:39
This issue happens to me again today for no reason. I didn't change anything in my code. Last time it disappeared automatically in a few hours. I hope this time would be the same, or I have no idea what to fix. I'm using SDK v2.6.1.

**Comment by Hemant0601** [comment] 2016-11-26 13:09
@lojol try updating to 3.0,  a lot of good updates are there.

**Comment by lojol** [comment] 2016-11-26 15:13
@Hemant0601 The issue was gone itself in a few hours as I expected. So there should be something unusual out of the app. Last time I met this issue was 2-3 months ago. I'll try updating to 3.0 next round.

**Comment by Hemant0601** [comment] 2016-11-27 17:24
@lojol yes the bad thing about most of the issues r that they r uncontrollable, and also most of them create direct app crash. Its too risky smtym to use QB

**Comment by vfite** [comment] 2017-02-09 10:07
Closed as for inactivity

**Closed by vfite** 2017-02-09 10:07 UTC
