### ISSUE TITLE
Local Video rotated by 180 degree

### ISSUE THREAD

**Issue by shoaibhassan1** [QuickBlox/quickblox-android-sdk#727] opened 2020-09-15 07:55 UTC
When i initiate a video call and change device orientation from portrait to landscape (left or right)
then local video gets rotated by 180 degree 
also other peer can see my video rotated.
Please help.

**Comment by alexparvus1** [comment] 2020-11-03 12:37
Please provide additional information, such as logs and more clear steps to reproduce.

**Comment by avinashyerrala** [comment] 2021-06-03 20:23
This is how I rotated my local video 90 degrees. Hope it helps someone looking for the answer.

 private fun fillVideoView(
        videoView: QBRTCSurfaceView, videoTrack: QBRTCVideoTrack,
        remoteRenderer: Boolean
    ) {
        videoTrack.removeRenderer(videoTrack.renderer)
        if (!remoteRenderer) {
            localVideoTrack?.track?.addSink { videoFrame->
                localVideoView.onFrame(VideoFrame(videoFrame.buffer, 90, -1))
            }
            val scalingType = RendererCommon.ScalingType.SCALE_ASPECT_FILL
            videoView.setScalingType(scalingType)
            videoView.setMirror(true)
            videoView.requestLayout()
        }else{

            videoTrack.addRenderer(videoView)
        }
        Log.d(TAG, (if (remoteRenderer) "remote" else "local") + " Track is rendering")
    }

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 15:02
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:12 UTC
