### ISSUE TITLE
Base Forbidden, Need User

### ISSUE THREAD

**Issue by Ahmadpashaquarterpi** [QuickBlox/quickblox-android-sdk#763] opened 2021-07-20 12:36 UTC
**QB Sdk version:** '3.9.11'

**Problem:** "Base Forbidden, Need User" and Sometime I also face problems while logging into the app.

**Duration:** Facing this problem since last week.

**Detail:** I have a testing account of quickblox and been working on this app fine. but started facing this issue last week. while I did not made any changes to the login method. 

**Question:** Does it has anything to do with testing account? like it has specific time duration or specific number of logins. Or is it entirely a different issue.
If its an issue on my side please guide me.

**P.s.:** I have planned to buy the enterprise package and about to launch my app. So Please Reply fast.

**Code:**
Heres my signIn method:
private void signIn(final QBUser user) {

        showProgressDialog(R.string.dlg_login);

        ChatHelper.getInstance().login(user, new QBEntityCallback<QBUser>() {

            @Override
            public void onSuccess(QBUser userFromRest, Bundle bundle) {

                if (userFromRest.getLogin().equals(user.getLogin())) {

                    loginToChat(user, false);
                } else {

                    
                    user.setPassword(null);
                    updateUser(user);
                }
            }

            @Override
            public void onError(QBResponseException e) {

                if (e.getHttpStatusCode() == UNAUTHORIZED) {

                    ToastUtils.longToast(e.getMessage() + " please check your user name and password");
                    hideProgressDialog();
                    //signUp(user);
                } else {

                    hideProgressDialog();
                    showErrorSnackbar(R.string.login_chat_login_error, e, new View.OnClickListener() {

                        @Override
                        public void onClick(View v) {

                            signIn(user);
                        }
                    });
                }
            }
        });
    }

**Comment by vdovbnya-qb** [comment] 2021-07-21 10:02
@Ahmadpashaquarterpi Hello. Thanks for your issue.
We have some problems on the server, these problems are being solved. For more information, contact the support team.

**Comment by vineeshLee** [comment] 2021-07-22 06:27
hi same thing happening here too,
getting an exception com.quickblox.core.exception.QBResponseException: base Required session does not exist sometimes ,
and also getting Base Forbidden, Need User ,

**Comment by QB-maksym-pidhorbunskyi** [comment] 2021-07-22 07:57
Hello @vineeshLee @Ahmadpashaquarterpi This is Maksym from QuickBlox support.
This is a known issue for QuickBlox Development team, you could experience such behavior from time to time while using QuickBlox Cloud infrastructure due to the internal bugs that contain the latest release that was deployed a few days ago.
Currently our backend developers are fixing the correct work of QuickBlox Cloud infrastructure and key functionalities there.
The approximate ETA for a new release with the fix is Thursday-Friday.
If you would like to receive an update when this issue is fixed, please [submit a ticket](https://help.quickblox.com/conversation/new) to the Help Center.
Take our apologies for possible inconveniences.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:38
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:38 UTC
