### ISSUE TITLE
com.quickblox.core.exception.QBResponseException: Client is not, or no longer, connected.

### ISSUE THREAD

**Issue by YogeshJ241** [QuickBlox/quickblox-android-sdk#700] opened 2020-03-14 07:00 UTC
Hello Team,

I am getting this type of issue while sending the message.

I have used the following method to send message.

public void sendMessage(QBChatDialog dialog, String message, QBEntityCallback<ArrayList<QBChatMessage>> callback) {

        ArrayList<Integer> occupantIdsList = new ArrayList<>();
        occupantIdsList.add(dialog.getUserId());
        QBChatDialog chatDialog = new QBChatDialog();
        chatDialog.setName(dialog.getName());
        chatDialog.setType(QBDialogType.PRIVATE);
        chatDialog.setOccupantsIds(occupantIdsList);

        QBChatMessage chatMessage = new QBChatMessage();
        chatMessage.setBody(message);
        chatMessage.setSaveToHistory(true);
        chatMessage.setDateSent(System.currentTimeMillis() / 1000);
        chatMessage.setMarkable(true);

        chatDialog.sendMessage(chatMessage, new QBEntityCallback<Void>() {
            @Override
            public void onSuccess(Void aVoid, Bundle bundle) {
                AppLog.e("onSuccess", new Gson().toJson(bundle));
            }

            @Override
            public void onError(QBResponseException e) {
                AppLog.e("onError", e.toString());
            }
        });

        // dialog.initForChat(QBChatService.getInstance());

        /*QBChatMessage chatMessage = new QBChatMessage();
        chatMessage.setBody(message);
        dialog.chatDialog(chatMessage, new QBEntityCallback<Void>() {
            @Override
            public void onSuccess(Void aVoid, Bundle bundle) {
                AppLog.e("onSuccess", new Gson().toJson(bundle));
            }

            @Override
            public void onError(QBResponseException e) {
                AppLog.e("onError", e.toString());
            }
        });*/
    }
![Capture](https://user-images.githubusercontent.com/16831197/76677041-6c7de300-65ef-11ea-8ef5-eac75c7a420c.PNG)
![Capture](https://user-images.githubusercontent.com/16831197/76677056-8c150b80-65ef-11ea-9078-16b490512d5c.PNG)

**Comment by OmarKRostom** [comment] 2020-03-27 07:37
I am having the same issue as well.

**Comment by QB-vladyslav-vyshniak** [comment] 2020-04-09 08:41
Hello @YogeshJ241 and @OmarKRostom 

The reported issue occurs when the connection with the server is lost, in this case you should reconnect to the chat. 
Use the following documentation to fix the issue on your side: 
1. https://docs.quickblox.com/docs/android-chat#section-connect-to-chat-server
2. https://docs.quickblox.com/docs/android-chat#section-disconnect-from-chat-server
3. https://docs.quickblox.com/docs/android-chat#section-autoreconnect-to-chat
4. https://docs.quickblox.com/docs/android-chat#section-chat-in-background

Please find the correct flow of sending the message below.
1. Create dialog and make a request to the server to make sure that dialog is created there. 
2. Send a message there. 

Let me know if you have any additional questions.

**Comment by alexparvus1** [comment] 2020-04-14 16:25
It seems that your application is not connected to the Chat Server. Please make reconnect if this connection is lost after long application foreground inactivity.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 14:04
@YogeshJ241 @OmarKRostom Hello,

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous replies and try the provided suggestions.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:30
@YogeshJ241 @OmarKRostom The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:30 UTC
