### ISSUE TITLE
Video call connction issue

### ISSUE THREAD

**Issue by arusyakhov** [QuickBlox/quickblox-android-sdk#746] opened 2021-02-03 08:22 UTC
I've integrated qb android sdk 3.9.10 to my project. In some rare cases I get issue with video call connection

**Environment details**
*(Operating system, browser information, SDK version)*
Operating System: Android
SDK Version: 3.9.10

**Did this work before?**
No

**Expected behavior**
When user answer's to opponent's call they should be connected

**Actual behavior**
In some rare cases the users don't get conncted

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
User A calls user B. User B gets call, accepts, but 2 users don't get connected - onRemoteVideoTrackReceive , onConnectedToUser and onCallAcceptByUser callbacks do not get triggered.

**Any others comments?**

**Comment by alexparvus1** [comment] 2021-03-04 19:24
@arusyakhov Please note that if you try to connect 3 or 4 devices in one call - and if these devices connected to the same wi-fi access point - it can overload your network and some part of your traffic can be lost. So please try to connect your devices through different networks - and all will work fine!

**Comment by arusyakhov** [comment] 2021-05-04 09:38
Hi. Thanks for the answer. I encounter it with 2 devices connected to the same wi-fi access point. And it happens in very rare cases.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 16:41
Hello @arusyakhov 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:11
@arusyakhov  The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:11 UTC
