### ISSUE TITLE
getDialogMessages is very slow take more than 5s , other methods like getChatDialogs are also not happy with quickblox performance specially in Android

### ISSUE THREAD

**Issue by ShubhGar** [QuickBlox/quickblox-android-sdk#750] opened 2021-03-04 17:26 UTC
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by alexparvus1** [comment] 2021-03-04 20:07
Maybe you caught the moment of a huge load on the QuickBlox shared server. It's normal when a lot of developers from all over the world use free QuickBlox Servers. Because almost all are free, all functionality is free. It's good for all free developers! But some developers sometimes make the servers overloaded. 
So please be careful with making frequent requests to the server. It can be harmful to all free applications based on free Quickblox servers.

**Comment by ShubhGar** [comment] 2021-03-05 04:32
But i purchased startup plan of quickblox, its not a free version. And its not only for our app your dummy android app also take lots of time.

**Comment by ShubhGar** [comment] 2021-03-07 10:15
@alexparvus1  I have startup plan of quickblox, but its really slow, calling chatting, history, everything slow.

**Comment by alexparvus1** [comment] 2021-03-07 13:17
@ShubhGar Yes, ut are you using your own paid QuickBlox API and Chat Servers?

**Comment by ShubhGar** [comment] 2021-03-08 04:51
@alexparvus1 , Yes i am using paid Quickblox API, Username: iamchirppie.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 13:01
@ShubhGar Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if you submitted a request to [https://help.quickblox.com/](https://help.quickblox.com/)

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:10
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:10 UTC

**Comment by umangnine** [comment] 2022-11-21 10:49
This issue is still relevant! We are facing same issue on Android platform! It works fine on iOS but on Android it is very very slow! Please let us know how we can resolve it?
