### ISSUE TITLE
Getting Unexpected Signature

### ISSUE THREAD

**Issue by Akash-DNA** [QuickBlox/quickblox-android-sdk#724] opened 2020-08-29 07:08 UTC
I am trying to merge quickblox in my project but while creating the session using API but getting "Unexpected Signature" 
using this Javascript for signature generation 

 <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.js"></script>

here is my javacode :

 $scope.CreateSession = function()
    
    {
        var n = Math.round(+new Date() / 1000);

        var Nonce = parseInt(n);
        var appid = 85640;
        var auth_key = "TNL6vCgyOP3es2p";
        var auth_sec = "F2puwTQ9-MJYMx-";
      
        var t = Math.round(+new Date() / 1000);
        var timestamp = parseInt(t);
        var message = "application_id=" + appid + "&auth_key=" + auth_key + "&nonce=" + Nonce + "&timestamp=" + timestamp;
        var signature = CryptoJS.HmacSHA256(message, auth_sec).toString(CryptoJS.enc.Hex);
       
        var parameter = {
            application_id: appid,
            auth_key: auth_key,
            timestamp: timestamp,
            nonce: Nonce,
            signature: signature
        }

        $.ajax({
            type: "POST",
            url: "https://api.quickblox.com/session.json",
            // url: "https://api.quickblox.com/users.json",
            contentType: "application/Json;Charset=utf-8",
            dataType: "Json",
            data: JSON.stringify(parameter),
            success: function (data) {
                $scope.Data = data;
            },
            error: function (data, Success, error) {
                //alert("Error : Something went wrong");
            }
        });
    }

**Comment by alexparvus1** [comment] 2020-11-03 12:33
I think we need more information to help you.
When you get an error? Why did you use a javascript signature in the android project? How did you merge your project with quickblox?

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 15:01
Hello

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply. Please provide us with the requested points.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:35
@Akash-DNA The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:35 UTC
