### ISSUE TITLE
How can i close AppRTCProximitySensor?

### ISSUE THREAD

**Issue by hasan5151** [QuickBlox/quickblox-android-sdk#757] opened 2021-05-11 06:59 UTC
When i init AppRTCAudioManager.create(context), AppRTCProximitySensor automatically start. I don't want to use AppRTCProximitySensor . Is there any function to close AppRTCProximitySensor ?

**Comment by alexparvus1** [comment] 2021-05-11 15:01
If you want to enable/disable managing speakerphone by proximity sensor you should use:
```
appRTCAudioManager = AppRTCAudioManager.create(this);
appRTCAudioManager.setManageSpeakerPhoneByProximity(false);
```
but it is FALSE (managing turned off) by default.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 13:13
@hasan5151 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if you checked the reply and if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:11 UTC
