### ISSUE TITLE
XMPP Error while creating Entry in QBRoster

### ISSUE THREAD

**Issue by ghost** [QuickBlox/quickblox-android-sdk#691] opened 2019-11-20 12:23 UTC
Hello,
I'm trying to configure the user (opponent) presence using QUICK-BLOX sdk(android). I've followed your documentation and implemented this after successful chat login:

```
qbRoster = chatService.getRoster(QBRoster.SubscriptionMode.mutual, subscriptionListener);
        if (qbRoster != null) {
            qbRoster.addRosterListener(rosterListener);
            if (qbRoster.contains(currentUser.getId())) {
                try {
                    qbRoster.subscribe(currentUser.getId());
                } catch (SmackException.NotConnectedException e) {
                    e.printStackTrace();
                }
            } else {
                qbRoster.createEntry(currentUser.getId(), null, new QBEntityCallback<Void>() {
                    @Override
                    public void onSuccess(Void aVoid, Bundle bundle) {
                    }
                    @Override
                    public void onError(QBResponseException e) {
                        Log.e("Qb Roster", e.getLocalizedMessage());
                    }
                });
            }
        }
```

But I'm getting XMPP Error every time saying "**xmpperror not-allowed - cancel**". I need help on it !!

**Comment by alexparvus1** [comment] 2020-04-14 16:57
Please provide logs if this issue is still relevant.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 09:59
The issue is closed as it is outdated and the user is deleted

**Closed by QB-nikolay-zolotarov** 2021-10-04 09:59 UTC
