### ISSUE TITLE
I can't download image file from custom object.

### ISSUE THREAD

**Issue by bailang1208** [QuickBlox/quickblox-android-sdk#692] opened 2020-01-09 20:46 UTC
Hello.
I uploaded png file on admin panel.
And I'm trying to download that image file.

QBCustomObjectsFiles.downloadFile(obj, "image").performAsync(new QBEntityCallback<InputStream>() {
            @Override
            public void onSuccess(InputStream inputStream, Bundle bundle) {
                Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
            }

            @Override
            public void onError(QBResponseException e) {

       }
});

When I am trying inputstream to bitmap, bitmap is null.
I don't know the reason.
Please help me.

**Comment by alexparvus1** [comment] 2020-04-14 16:55
You should use for example AsyncTask to save inputStream to file in the background.
For example: 
```
    private class InputStreamReaderAsyncTask extends AsyncTask<Void, Void, Boolean> {
        private InputStream inputStream;
        private File file;
        
        InputStreamReaderAsyncTask(InputStream inputStream, File file) {
            this.inputStream = inputStream;
            this.file = file;
        }

        @Override
        protected Boolean doInBackground(Void... voids) {
            try {
                FileOutputStream output = new FileOutputStream(file);

                if (inputStream != null) {
                    IOUtils.copy(inputStream, output);
                    inputStream.close();
                    output.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
                return false;
            }
            return true;
        }

        @Override
        protected void onPostExecute(Boolean result) {
            if (result) {
                // Successfully loaded
            } else {
                // Loading Error
            }
        }
    }
```

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 10:03
@bailang1208 Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if you had a chance to check the previous comment and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:12 UTC
