### ISSUE TITLE
Microphone issue during video/audio call

### ISSUE THREAD

**Issue by arusyakhov** [QuickBlox/quickblox-android-sdk#708] opened 2020-05-27 08:28 UTC
i face a problem with microphone on Xiaomi Pocophone f1 Android 10. The voice from this client's side is not heard and the other client cannot hear the voice coming from this client either.

**Comment by alexparvus1** [comment] 2020-06-03 10:14
Please clarify your issue. 
1. Does this problem reproduce on all android devices you try?
2. Please check the microphone permission in your application.

**Comment by arusyakhov** [comment] 2020-06-16 11:42
Hello
1. The problem doesn't occur on all android devices
2. microphone permission is enabled

**Comment by alexparvus1** [comment] 2020-06-25 18:04
1. Could you please give the current firmware version of this Poco F1? Does it work on Xiaomi's stock firmware for the Poco-series or Xiaomi MIUI build? Maybe it works on Black-Shark firmware edition or other custom firmware? (Please provide a version)

2. Did it work fine if the Pocophone user switched on a headset with an external microphone? (or Bluetooth headset?)

3. Does the application on Poco use an AEC function? (Audio Echo Cancellation) ( `QBRTCMediaConfig.setUseBuildInAEC(true/false);` ) Did you try to change this parameter?

4. Sound from Poco is completely absent? Even if someone hits microphone-hole on Poco? (Poco has an additional mic for noize reduction, and you need to be sure that echo cancellation works fine on this device) 

5. Could you please show an audiotrack stats form Xiaomi Poco F1 when this device is on the call with your test device?
I mean:
```
qbrtcStatsReport.getAudioReceiveOutputLevel();
qbrtcStatsReport.getAudioReceivedBitrate();
qbrtcStatsReport.getAudioReceivedCodec();
qbrtcStatsReport.getAudioReceivedCurrentDelay();
qbrtcStatsReport.getAudioReceivedPacketsLost();
qbrtcStatsReport.getAudioReceivedPacketsReceived();
qbrtcStatsReport.getAudioReceivedExpandRate();
qbrtcStatsReport.getAudioReceivedTrackId();
```
in your onStatsReportUpdate callback.

How to get a Stats Report: https://docs.quickblox.com/docs/android-video-calling-advanced#webrtc-stats-reporting

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 14:28
Hello @arusyakhov 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If yes, please provide us with the points requested in the previous reply.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:12 UTC
