### ISSUE TITLE
QBUsers.getUsersByFullName is not giving proper result for 1 or 2 letters of input (search query)

### ISSUE THREAD

**Issue by sagarpatel288** [QuickBlox/quickblox-android-sdk#744] opened 2021-02-01 07:22 UTC
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*

**Environment details**
*(Operating system, browser information, SDK version)*
Operating System: Android
SDK Version: 3.9.2

**Did this work before?**
No

**Expected behavior**
Even if the search query contains only 1 or 2 letters, it should give all the users whose full name contains those letters.

**Actual behavior**
It is working perfectly if the search query contains at least 3 or more letters. But, If there are two names: "Sagar Patel" and "Patel Sagar D", it is showing the result for "Patel Sagar D" only for the search query "pat". It should include "Sagar Patel" also. (However, it includes both if the search query is "pate").

**Logs**
*(please, use github [gist](https://gist.github.com/))*
Could not figure out what kind of logs can be helpful here. But, will update if required.

**Steps to reproduce the behavior**
Go to ```SelectUsersActivity``` of an existing android kotlin demo project and change the value of:
```MIN_SEARCH_QUERY_LENGTH``` from 3 to 1 or try with any search query having 3 letters while having names that contain letters of the search query after space in the name.

**Any others comments?**

**Comment by alexparvus1** [comment] 2021-03-04 19:13
@sagarpatel288  Please note, that the minimum search phrase must contain at least 3 characters. It's the server's restriction to prevent overloading the shared free server. And this is normal practice because searching by a single letter will not return relevant answers if you have a lot of users.

**Comment by sagarpatel288** [comment] 2021-03-08 12:43
@alexparvus1 Even when we are using 3 characters, If there are two names: "Sagar Patel" and "Patel Sagar D", it is showing the result for "Patel Sagar D" only for the search query "pat". **It should include "Sagar Patel" also.** (However, it includes both if the search query is "pate" - that are a total of 4 characters).

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 16:37
Hello @sagarpatel288 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:11
@sagarpatel288  The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:11 UTC
