### ISSUE TITLE
qbchatservice: onError: Authentication failed, check user's ID and password

### ISSUE THREAD

**Issue by Firdausfatihul** [QuickBlox/quickblox-android-sdk#697] opened 2020-02-19 03:59 UTC
**Environment details**
*(Operating system, browser information, SDK version)*
OS : Windows 10
Browser: Chroome

**Did this work before?**
No

**Expected behavior**
create session for chat

**Actual behavior**
qbschatservice: onError: Authentication failed, check user's ID and password

**Logs**
`private void createSessionForChat() {
        final ProgressDialog mDialog = new ProgressDialog(ChatDialogActivity.this);
        mDialog.setMessage("Please waiting.....");
        mDialog.setCanceledOnTouchOutside(false);
        mDialog.show();

        String user,password;
        user = getIntent().getStringExtra("user");
        password = getIntent().getStringExtra("password");
        final QBUser qbUser = new QBUser(user,password);
        QBAuth.createSession(qbUser).performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                qbUser.setId(qbSession.getId());
                try {
                    qbUser.setPassword(BaseService.getBaseService().getToken());
                } catch (BaseServiceException e) {
                    e.printStackTrace();
                }

                QBChatService.getInstance().login(qbUser, new QBEntityCallback() {
                    @Override
                    public void onSuccess(Object o, Bundle bundle) {
                        mDialog.dismiss();
                    }

                    @Override
                    public void onError(QBResponseException e) {
                        Log.d("qbschatservice", "onError: " + e.getMessage());
                        
                    }
                });
            }

            @Override
            public void onError(QBResponseException e) {

            }
        });
    }`

How do i fix this?

**Comment by alexparvus1** [comment] 2020-04-14 16:38
You try to login to Chat Server (QBChatService.getInstance().login) with an unexisting user.
It is simpler to make login logic using:
`    private void signIn(QBUser qbUser) {
        QBUsers.signIn(qbUser).performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser qbUser, Bundle bundle) {
                loginToChat(qbUser);
            }

            @Override
            public void onError(QBResponseException e) {

            }
        });
    }
    
    private void loginToChat(QBUser qbUser) {
        QBChatService.getInstance().login(qbUser, new QBEntityCallback() {
            @Override
            public void onSuccess(Object o, Bundle bundle) {
                // Successful login
            }

            @Override
            public void onError(QBResponseException e) {

            }
        });
    }`

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 11:18
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if you had a chance to check the previous comment and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:12 UTC
