### ISSUE TITLE
Cannot upload file with length less than 1kb

### ISSUE THREAD

**Issue by gurinovich89** [QuickBlox/quickblox-android-sdk#709] opened 2020-06-01 08:51 UTC
I am trying to upload small text file(less than 1kb) to quickBlox as file attachment but I got error
```
com.quickblox.core.exception.QBResponseException: size should be greater than 1 KB
```
For uploading I use these code
```
QBContent.uploadFileTask(file, true, null, progressCallback).performAsync(...)
```
Is it possible to upload small files to quicblox and how I can do it?

**Comment by alexparvus1** [comment] 2020-06-01 12:59
Thank you for your question!
Unfortunately, this is a restriction for all users now - file size should be greater than 1Kb

**Comment by alexparvus1** [comment] 2020-06-04 14:01
@gurinovich89 This restriction was changed! Now minimum file size is reduced to 1 byte.
Thank You for using QuickBlox Android SDK. Have a nice day

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 14:29
@gurinovich89 Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:12 UTC
