### ISSUE TITLE
Cannot accept Videocall in Android SDK

### ISSUE THREAD

**Issue by billypap1** [QuickBlox/quickblox-android-sdk#760] opened 2021-06-21 10:36 UTC
**Environment details**
*(Operating system, browser information, SDK version)*
Android 10 - QuickBlox Android SDK v.3.9.0

**Did this work before?**
No

**Expected behavior**
User accept call and connect to videocall

**Actual behavior**
User can receive a call, but when he accepts call, the caller don't receive the accept event.

**Any others comments?**

The call is from web sdk js to android SDK and the state is always -> RTC_SESSION_CONNECTING without progress. Is this a bug?

**Comment by kirillTolmachev** [comment] 2021-07-09 09:23
@billypap1 Hello.
Please provide more information like logs from Android Studio and steps.
Please reproduce this issue in our video call sample https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-kotlin

**Comment by aakash232** [comment] 2021-09-06 04:17
**You can try and match with this code. This fixed the issue.

- Attach addSessionCallbackListener to your QBRTCClient.
- Under onReceiveNewSession**

QBRTCClient.getInstance(getApplicationContext()).addSessionCallbacksListener(new QBRTCClientSessionCallbacks() {
            @Override
            public void onReceiveNewSession(QBRTCSession qbrtcSession) {

                Map<String, String> userInfo = new HashMap<>();
                userInfo.put("key", "value");

                AlertDialog.Builder builder = new AlertDialog.Builder(VideoCall.this);
                builder.setMessage("Received a video call")
                        .setPositiveButton("Accept", new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {

             
                                qbrtcSession.acceptCall(userInfo);


                                _/*
                                 *  Attach addSessionCallbacksListener to your session
                                 * Make the further changes as you want during connection and after connection
                                 */_

                                qbrtcSession.addSessionCallbacksListener(new QBRTCSessionConnectionCallbacks() {
                                    @Override
                                    public void onStartConnectToUser(QBRTCSession qbrtcSession, Integer integer) {
                                        ProgressDialog mDialog = new ProgressDialog(VideoCall.this);
                                        mDialog.setMessage("Please wait. Starting connection...");
                                        mDialog.setCanceledOnTouchOutside(false);
                                        mDialog.show();
                                        qbrtcSession.acceptCall(userInfo);
                                        addVideo();
                                        addAudio();

                                    }

                                    @Override
                                    public void onDisconnectedTimeoutFromUser(QBRTCSession qbrtcSession, Integer integer) {
                    
                                    }

                                    @Override
                                    public void onConnectionFailedWithUser(QBRTCSession qbrtcSession, Integer integer) {
                                        Log.d("ERROR", "Connection Failed with user");
                            
                                    }

                                    @Override
                                    public void onStateChanged(QBRTCSession session, BaseSession.QBRTCSessionState qbrtcSessionState) {

                                    }

                                    @Override
                                    public void onConnectedToUser(QBRTCSession session, Integer integer) {
                                        session.acceptCall(userInfo);
                                        mDialog.dismiss();
                                    }

                                    @Override
                                    public void onDisconnectedFromUser(QBRTCSession session, Integer integer) {
                                        Log.d("ERROR", "Disconnected from user");
                                    }

                                    @Override
                                    public void onConnectionClosedForUser(QBRTCSession session, Integer integer) {

                                    }
                                });
                            }
                        })
                        .setNegativeButton("Decline", new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                dialog.dismiss();
                                qbrtcSession.rejectCall(userInfo);
                            }
                        })
                        .setCancelable(true);

                AlertDialog alertDialog = builder.create();
                alertDialog.show();

            }

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 13:28
Hello,  @billypap1 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:11 UTC
