### ISSUE TITLE
Video calling - UnsatisfiedLinkError in PeerFactoryManager

### ISSUE THREAD

**Issue by AustrianDudes** [QuickBlox/quickblox-android-sdk#742] opened 2021-01-22 14:32 UTC
Dear Quickblox team,
I'm currently experiencing following crash on my new development tablet (arm64) when starting a new WebRTC video call or accepting an incoming video call:

`1698-3490/com.ilogs.products.moccajames E/org.webrtc.Logging: NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ilogs.products.moccajames-sTjI8mtyWlYejcZdhyaxVA==/base.apk"],nativeLibraryDirectories=[/data/app/com.ilogs.products.moccajames-sTjI8mtyWlYejcZdhyaxVA==/lib/arm64, /system/lib64, /vendor/lib64]]] **couldn't find "libjingle_peerconnection_so.so"**
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
        at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:294)
        at **com.quickblox.videochat.webrtc.PeerFactoryManager.initPeerConnectionFactory(PeerFactoryManager.java:149)**
        at com.quickblox.videochat.webrtc.PeerFactoryManager.access$100(PeerFactoryManager.java:25)
        at com.quickblox.videochat.webrtc.PeerFactoryManager$1.run(PeerFactoryManager.java:100)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
` 

I am using the newest release 3.9.10. I saw in your pom file for this release that you have following dependency:

`<dependency>
      <groupId>org.webrtc</groupId>
      <artifactId>google-webrtc</artifactId>
      <version>1.0.25003</version>
      <scope>compile</scope>
</dependency>`

As this version was released in 2018 maybe updating the dependency to the newest version 1.0.32006 in your sdk solves this issue?

Hope to hear from you soon,
Pierre

**Comment by alexparvus1** [comment] 2021-01-22 16:51
Thank you for your question. Please provide your device model and give more logs to help us understand the problem with webRTC on your device. Thanks

**Comment by AustrianDudes** [comment] 2021-01-25 09:24
Hi, thanks for your quick response.
The device effected by this issue is a E101GC4G with Android 8.1.0 installed. As supported abi architectures the device returns "arm64-v8a, armeabi-v7a and armeabi".

It seems as the PeerFactoryManager tries to located the libjingle_peerconnection_so.so file in the /lib/arm64 folder, but the folder has not been generated. To my understanding these native library is added by the google-webrtc library included in your quickblox library. Maybe a newer included google-webrtc library generates a proper result?

Hope to hear from you soon,
Kind regards, Pierre

**Comment by stephanoparaskeva** [comment] 2021-05-11 17:47
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 16:31
Hello

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:12
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:12 UTC
