### ISSUE TITLE
Video Call issues

### ISSUE THREAD

**Issue by arusyakhov** [QuickBlox/quickblox-android-sdk#745] opened 2021-02-03 08:16 UTC
When the user is connected to bluetooth airpods, video call drops after some seconds of call. QBRTCSessionStateCallback onDisconnectedFromUser gets called. 

**Environment details**
*(Operating system, browser information, SDK version)*
Operating System: Android
SDK Version: 3.9.10

**Did this work before?**
not sure

**Expected behavior**
The call should not drop if one of the clients is connected by bluetooth airpods.

**Actual behavior**
It works without call drops if not connected by bluetooth airpods

**Logs**
*(please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Connect the android device to bluetooth airpods, make a call, after the opponent accepts, wait some seconds, then the call drops. It's possible to reproduce the issue with Quckblox video chat kotlin sample

**Any others comments?**
Xiaomi Android 10, quickblox sdk version 3.9.10

**Comment by alexparvus1** [comment] 2021-03-04 19:17
It's good that you found this issue, but to help you we need some logs to determine the thing which makes the call ending. 
It seems that your AirPods was sent a "Call Hangup" signal to the system. 
Please provide the logs if possible.

**Comment by arusyakhov** [comment] 2021-05-04 09:36
Hi, thanks for the answer. You can check it on qb video chat sample, where I encounter the same issue. Anyway if you think the issue is connected with my environment, let me know, I'll try to provide the logs.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 16:39
@arusyakhov Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:11
@arusyakhov  The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:11 UTC
