### ISSUE TITLE
Call Recording Issue One Side Gets Recorded

### ISSUE THREAD

**Issue by waqarYasin** [QuickBlox/quickblox-android-sdk#759] opened 2021-05-21 09:50 UTC
I have been trying this issue but same response when i start recording it only records my voice but don't record other side voice 
but i am facing this issue in android 10 ..Realme Note 9 Device 

**Expected behavior**
Should record both side voice

**Actual behavior**
only record caller side receiver side voice is not recorded.

**Comment by alexparvus1** [comment] 2021-05-26 10:38
Please provide more information! What functionality did you use to make a call? How did you record the call? What are errors did you get in your code?

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 13:26
@waqarYasin 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if you checked the previous reply.

The feature of recording audio/video calls is available only for conference calls.
Conference audio/video calls functionality is provided as an addon for all paid plans.
You may read more here:
[https://quickblox.com/pricing/](https://quickblox.com/pricing/)
In order to use the video conference calling feature, you need to purchase a dedicated Janus server.

Server side recording functionality can be enabled/disabled for the entire server from our side. Every call will be recorded if the feature is enabled.

Audio and video files are recorded for each user separately and stored on the server.

If you are interested in audio/video conference functionality and call recording, feel free to [contact our Sales team](https://quickblox.com/enterprise/#get-enterprise) to get more information.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:11 UTC
