### ISSUE TITLE
QBJsonErrorParser parse error

### ISSUE THREAD

**Issue by FisnikIbishi** [QuickBlox/quickblox-android-sdk#734] opened 2020-11-09 19:23 UTC
I get com.quickblox.core.parser.QBJsonErrorParser.parseError (QBJsonErrorParser.java:79) o release build. On debug it works fine

**Comment by hassanmhd** [comment] 2020-11-14 09:33
> I get com.quickblox.core.parser.QBJsonErrorParser.parseError (QBJsonErrorParser.java:79) o release build. On debug it works fine

I was facing the same issue. It's because some of the classes were obfuscated by proguard.
A quick solution is to exclude quickblox's  classes by adding the following to the end of your proguard rules

```
-keep class com.quickblox.auth.parsers.** { *; }
-keep class com.quickblox.auth.model.** { *; }
-keep class com.quickblox.core.parser.** { *; }
-keep class com.quickblox.core.model.** { *; }
-keep class com.quickblox.core.server.** { *; }
-keep class com.quickblox.core.rest.** { *; }
-keep class com.quickblox.core.error.** { *; }
-keep class com.quickblox.core.Query { *; }

-keep class com.quickblox.users.parsers.** { *; }
-keep class com.quickblox.users.model.** { *; }

-keep class com.quickblox.chat.parser.** { *; }
-keep class com.quickblox.chat.model.** { *; }

-keep class com.quickblox.messages.parsers.** { *; }
-keep class com.quickblox.messages.model.** { *; }

-keep class com.quickblox.content.parsers.** { *; }
-keep class com.quickblox.content.model.** { *; }

-keep class org.jivesoftware.** { *; }
```

**Comment by alexparvus1** [comment] 2021-01-20 15:07
@FisnikIbishi  yes, in case of similar problems you should look into your proguard rules in your project as @hassanmhd posted.
Thanks @hassanmhd !

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 15:14
Hello @FisnikIbishi 

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous replies and resolve the issue.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by FisnikIbishi** [comment] 2021-10-04 15:18
Fixed, thanks :)

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 15:22
@FisnikIbishi You are most welcome. Thank you for notifying me.

The issue is being closed.

**Closed by QB-nikolay-zolotarov** 2021-10-04 15:22 UTC
