### ISSUE TITLE
USB Webcam access using quickblox android sdk 

### ISSUE THREAD

**Issue by ShreeKrish** [QuickBlox/quickblox-android-sdk#728] opened 2020-09-20 12:16 UTC
Is there a way to access USB logitech webcam connected to Android Phone using quickblox android sdk.
Currently it recognizes only inbuilt cameras

**Comment by alexparvus1** [comment] 2020-11-03 12:41
Please provide more info about Your "Android Phone", your "Logitech webcam", how did you connect these devices, and how Android device will recognize this device.

**Comment by ShreeKrish** [comment] 2020-11-10 10:19
Please find the details below :
- I am using USB C Hub Dock 8 in 1 Type C adapter. With this i am able to connect HDMI and logitech-C270 HD webcam.
- Able to get the stream from USB Camera app based on UVC. 

From my analysis, i think the quickblox webrtc package (Camer1Enumerator) only looks for connected devices on /dev/video nodes .. However, the USB based webcam is populated on /dev/bus/usb/. These camera devices are not considered.

Can you please let know if there is any way for me to hook to add logic to open camera devices connected on /dev/bus/usb nodes.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-04 15:08
Hello, @ShreeKrish 

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:36
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:36 UTC
