### ISSUE TITLE
How to send Video file and GIF file in QuickBlox chat Sdk Android

### ISSUE THREAD

**Issue by MahadevT** [QuickBlox/quickblox-android-sdk#404] opened 2017-05-23 09:55 UTC
Please can anyone guide me how to send video and GIF file in Quickblox android sdk

**Comment by tatanka987** [comment] 2017-05-23 10:47
hello @MahadevT, you can send any data using QuickBlox Android SDK. For it you can use QBAttachment for it, for details see [link](https://quickblox.com/developers/Android_XMPP_Chat_Sample#Send_and_receive_a_message_with_attachment). For displaying GIF files you can use [ChatMessagesAdapter](https://github.com/QuickBlox/ChatMessagesAdapter-android). But for displaying video files you have to create your own custom view.

**Comment by alexanderkoqb** [comment] 2019-01-22 16:58
Hey @MahadevT 
Closing the issue as a duplicate of #405

**Closed by alexanderkoqb** 2019-01-22 16:58 UTC
