### ISSUE TITLE
An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by hasan5151** [QuickBlox/quickblox-android-sdk#749] opened 2021-02-28 19:30 UTC
applicationId is null. You must call QBSettings.getInstance().init(Context, String, String, String) before using the QuickBlox library.

**Comment by alexparvus1** [comment] 2021-03-04 19:35
Yes, you should have even one "application" in QuickBlox Admin Panel. So you should register in QuickBlox before.
This information was in the repository and in the folder where you have downloaded the sample application. Also, this information you can find in QuickBlox Documentation - https://docs.quickblox.com/docs/android-setup

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 15:11
@hasan5151  The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 15:11 UTC
