### ISSUE TITLE
rtcClient.getSession("sessionId").isActive throw NullPointException

### ISSUE THREAD

**Issue by hasan5151** [QuickBlox/quickblox-android-sdk#752] opened 2021-04-21 10:32 UTC
rtcClient.getSession("sessionId").isActive throw NullPointException

**Comment by alexparvus1** [comment] 2021-05-07 18:10
It seems that there are no session found with this Session ID.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 13:03
Hello @hasan5151 

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:11 UTC
