### ISSUE TITLE
Delete Message Limit

### ISSUE THREAD

**Issue by hasan5151** [QuickBlox/quickblox-android-sdk#756] opened 2021-05-05 20:47 UTC
QBRestChatService.deleteMessages(messagesIDs, forceDelete).performAsync(object : QBEntityCallback<Void?> {
            override fun onSuccess(p0: Void?, p1: Bundle?) {
            }

            override fun onError(e: QBResponseException) {
            }
        })

Is there any delete message limit? How can i clear chat history? I can delete 5-10 messages but i couldnt delete 180 messages

**Comment by alexparvus1** [comment] 2021-05-07 14:42
Please provide the logs regarding this issue.

**Comment by hasan5151** [comment] 2021-05-07 17:39
com.quickblox.core.exception.QBResponseException: 
     at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source:49)
     at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source:24)
     at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source:11)
     at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source:46)
     at android.os.Handler.dispatchMessage(Handler.java:107)
     at android.os.Looper.loop(Looper.java:224)
     at android.app.ActivityThread.main(ActivityThread.java:7562)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by hasan5151** [comment] 2021-05-07 20:49
=== REQUEST ==== c8f50047-664d-4b75-9c14-e657fdab3adc === 
i sent delete 161 items. As i understand there is a limit for sent ids.

**Comment by hasan5151** [comment] 2021-05-07 20:50
*** RESPONSE *** c8f50047-664d-4b75-9c14-e657fdab3adc ***
    STATUS : 400 
    HEADERS
        X-Android-Selected-Protocol=http/1.1
        Server=nginx
        Connection=close
        X-Android-Response-Source=NETWORK 400
        X-Android-Sent-Millis=1620420279661
        Content-Length=0
        X-Android-Received-Millis=1620420280006
        Date=Fri, 07 May 2021 20:44:40 GMT
        Content-Type=application/json; charset=utf-8
    BODY
        ''

**Comment by hasan5151** [comment] 2021-05-07 20:50
But how can i delete all history chat?

**Comment by alexparvus1** [comment] 2021-05-11 12:10
As you can see - your request is too long - not all data contained in your request. So the server can not interact with just the part of the request. 
If you need to delete a lot of messages, it seems you should delete them assembling by 10 or 20.

**Comment by QB-nikolay-zolotarov** [comment] 2021-10-05 13:13
@hasan5151 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if you checked the previous reply and if the issue is still relevant.

If there is no reply within 5 business days, the issue will be closed as outdated.

**Closed** 2023-01-11 10:11 UTC
